apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie 
  template:
    metadata:
      labels:
        app: movie 
    spec:
      containers:
      - name: movie 
        image: paschalolo/movie:1.0.0
        imagePullPolicy : IfNotPresent
        ports:
        - containerPort: 8083
        resources:
          requests:
            cpu: "100m" # 100 millicores
            memory: "128Mi" # 128 mebibytes
          limits:
            cpu: "500m" # 500 millicores
            memory: "512Mi" # 512 mebibytes
